
import type { Metadata } from "next";
import { Geist, Geist_Mono, Fredoka, Quicksand } from "next/font/google";
import Navbar from "@/components/header/navbar";
import AnimatedBackground from "@/components/header/animation";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ["latin"],
});

const quicksand = Quicksand({
  variable: "--font-quicksand",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fredoka.variable} ${quicksand.variable} antialiased`}
      >
          <header className="sticky top-0 z-50 w-full bg-white backdrop-blur-md">
          <Navbar />
          </header>
          {children}

        <div className="fixed top-0 left-0 w-full h-full -z-10">
        <AnimatedBackground />
        </div>
      </body>

      

    </html>
  );
}
